
apiVersion: apps/v1
kind: Deployment
metadata:
   name: aks-helloworld

spec:
   replicas: 2
   selector:
       matchLabels:
             app: aks-helloworld


   template:
     metadata:
        labels:
          app: aks-helloworld

     spec:
       containers:
       - name: aks-helloworld
         image: acrimages2.azurecr.io/prathibhapadma/new-demo-app1:latest

         ports:
         - containerPort: 8082
