apiVersion: v1
kind: Secret
metadata:
  name: secret-basic-auth
type: kubernetes.io/basic-auth
stringData:
  server: acrimages2.azurecr.io
  username: acrimages2
  password: auVrzBVYZxPFdB3Eh8/CvaXVyKXfNtRs
